# Note: Passing settings as dict parameter directly has priority on this
# config file.

# ------------------------------ run.py -----------------------------------

# Always use specified host address without asking the user
always_at: null

# ----------------------------- server.py ---------------------------------

# Maximum number of concurrent users
max_conn: 20

# Available ports to use, will only attach to one, "auto" for random ports
avail_ports: [29111, 29112, 29113, 29114, 29115, 29116, 29117, 29118, 29119]

# Number of new user handlers, for concurrent user connection
new_conn_processes: 3

# Multiply all sleep() delays by this value
delay_factor: 0.0

# Allow two or more users from the same source IP address
allow_same_source_ip: true

# Blacklist of IP addresses on server startup
blacklisted: null

# Duration of the pause between games, the value at which countdown starts
lobby_time: 60

# ------------------------------ game.py ----------------------------------

# Number of rounds in one game
rounds: 5

# -------------------------------------------------------------------------
