name: Automatic Pre-Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Release Title
        id: get_title
        run: |
          NAME=$(awk -F "=" '/name/ {print $2}' setup.cfg | tr -d '[:space:]')
          VERSION=$(awk -F "=" '/^version/ {print $2}' setup.cfg | tr -d '[:space:]')
          echo "title=$NAME v$VERSION" >> $GITHUB_OUTPUT

      - name: Create Development Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "${{ steps.get_title.outputs.title }}"
          files: |
            LICENSE
            README.md
            dist/*
