name: Black

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/psf/black
    - name: Formatting the code with Black
      run: |
        black $(git ls-files '*.py')
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com
        message: "Formatting the code with Black"
        add: "."
        branch: ${{ github.ref }}
