name: "Format and lint (3.9)"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autoflake black isort pylint
    - name: Formatting the code (autoflake, black, isort)
      run: |
        isort $(git ls-files '*.py')
        autoflake $(git ls-files '*.py') --in-place --remove-all-unused-imports --remove-unused-variables --recursive
        black $(git ls-files '*.py')
    - name: Pushing formatted code
      continue-on-error: true # Prevent fail from no diff on output
      run: |
        git config --global user.name "format-and-lint-action"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "Format and lint run"
        git push
    - name: Evaluating pylint (all files)
      run: |
        pylint $(git ls-files '*.py') --disable=C0103 --fail-under=9
    - name: Pushing new pylint result to README.md (only nc-hangman.py)
      run: |
        pylintscore = $(pylint nc-hangman.py | grep 'Your code' | cut -c29-32)
        sed -i '4s/.*/[![pylint: $pylintscore]https://img.shields.io/badge/pylint-$pylintscore-1c7d9e.svg](https://github.com/magnetrwn/nc-hangman/actions)/' README.md
        git add README.md
        git commit -m "Format and lint run"
        git push
